### ISSUE TITLE
The CRC-16 of string name of Li is not the same, need to be verified.

### ISSUE THREAD

**Issue by bygreencn** [mattsta/crcspeed#2]
I have check more implements of CRC-CCITT 
  POLYNOMIAL:0x1021,
  INITIAL:0x0000,
 FINAL_XOR_VALUE:0x0000,
 Little endian.

For char test="123456789",  the crc result is # 0x31c3
For char li[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed "
                "do eiusmod tempor incididunt ut labore et dolore magna "
                "aliqua. Ut enim ad minim veniam, quis nostrud exercitation "
                "ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis "
                "aute irure dolor in reprehenderit in voluptate velit esse "
                "cillum dolore eu fugiat nulla pariatur. Excepteur sint "
                "occaecat cupidatat non proident, sunt in culpa qui officia "
                "deserunt mollit anim id est laborum.", the crc result is # 0x224f

you can check them:
[http://www.sunshine2k.de/coding/javascript/crc/crc_js.html](http://www.sunshine2k.de/coding/javascript/crc/crc_js.html)
[http://www.barrgroup.com/Embedded-Systems/How-To/CRC-Calculation-C-Code](http://www.barrgroup.com/Embedded-Systems/How-To/CRC-Calculation-C-Code)

So i think your result for string Li of 4b20 is not correct.

**Comment by bygreencn** [comment]
also i have checked Redis crc16 implement, the result is also 0x224f.
[https://github.com/antirez/redis/blob/28c291c55c35b8acaedffbb7eb98b3fc175e1237/src/crc16.c](https://github.com/antirez/redis/blob/28c291c55c35b8acaedffbb7eb98b3fc175e1237/src/crc16.c)

**Comment by mattsta** [comment]
Thanks for trying to spot an error!

The current code is _actually_ correct though.

The code tests the  *array size* of the string (**including** the null terminator at the end), so it's doing `crc16()` on a string of length 446 (string + `\0`) and NOT on a string of length 445 (just the text).

If you modify the test calculation to use `strlen()` or `sizeof(li) - 1` then the result matches what you expect elsewhere.
