### ISSUE TITLE
CRC16 test reports ERROR, likely because 32 bits are printed/used as CRC16 checksum

### ISSUE THREAD

**Issue by ZNikke** [mattsta/crcspeed#3]
The accelerated CRC16 implementation seems to be misbehaving. I get CRC errors regardless of which files are used, for the below examples I've used the 60k test file http://ftp.acc.umu.se/mirror/media/StarWreck-InThePirkinning/star_wreck_in_the_pirkinning_subtitles_eng.srt (Creative Commons licensed).

However, I think that the errors are benign as CRC16 is 2 bytes, and all mismatches I've seen seems to be in the additional 2 bytes that are emitted for some reason. Coding cleanup gone wrong?

I don't think it's a compiler/CPU-specific issue, as I'm seeing this on various machines. The examples below are a git pull of this repo and make clean; make to have the crc*speed-test binaries compiled on each platform.

RHEL 6.7, Intel E5-2643:
```
crc16 (no table)
CRC = 0000000022dda97d
0.002447 seconds at 23.98 MB/s (131.23 CPU cycles per byte)

crc16 (lookup table)
CRC = 000000002ddaa97d
0.000250 seconds at 234.70 MB/s (13.38 CPU cycles per byte)
ERROR: CRC results don't match! (0000000022dda97d vs. 000000002ddaa97d)

crc16speed
CRC = 000000002ddaa97d
0.000052 seconds at 1128.34 MB/s (2.80 CPU cycles per byte)
ERROR: CRC results don't match! (0000000022dda97d vs. 000000002ddaa97d)
```
Ubuntu 14.04.5 LTS, Intel E5-2630:
```
crc16 (no table)
CRC = 0000000022dda97d
0.004516 seconds at 12.99 MB/s (168.45 CPU cycles per byte)

crc16 (lookup table)
CRC = 000000002ddaa97d
0.000514 seconds at 114.15 MB/s (19.17 CPU cycles per byte)
ERROR: CRC results don't match! (0000000022dda97d vs. 000000002ddaa97d)

crc16speed
CRC = 000000002ddaa97d
0.000103 seconds at 569.65 MB/s (3.85 CPU cycles per byte)
ERROR: CRC results don't match! (0000000022dda97d vs. 000000002ddaa97d)
```
Ubuntu 16.04.2 LTS, Intel E5-2620 v4:
```
crc16 (no table)
CRC = 0000000022dda97d
0.004750 seconds at 12.35 MB/s (162.13 CPU cycles per byte)

crc16 (lookup table)
CRC = 000000002ddaa97d
0.000513 seconds at 114.37 MB/s (17.50 CPU cycles per byte)
ERROR: CRC results don't match! (0000000022dda97d vs. 000000002ddaa97d)

crc16speed
CRC = 000000002ddaa97d
0.000071 seconds at 826.39 MB/s (2.42 CPU cycles per byte)
ERROR: CRC results don't match! (0000000022dda97d vs. 000000002ddaa97d)
```

**Comment by mattsta** [comment]
Thanks for the detailed report and the perfect fix!

The idea was there, but it just got skipped over and never implemented properly for some reason (the tests never failed under OS X testing, so visually it "worked." yay cross platform compat!).
